import type { ChannelCategory } from "./enums";

const NICHE_TOPICS: Readonly<Record<ChannelCategory, ReadonlyArray<string>>> = {
  technology: [
    "system design", "microservices", "CI/CD pipelines",
    "Docker", "Kubernetes", "serverless",
    "TypeScript", "Rust", "Go", "Python",
    "React", "Vue", "Angular", "Svelte", "Next.js",
    "REST API design", "GraphQL", "WebSockets",
    "database design", "PostgreSQL", "MongoDB", "Redis",
    "testing strategies", "TDD", "E2E testing",
    "performance optimization", "caching strategies",
    "authentication", "OAuth", "JWT", "security best practices",
    "AI/ML in production", "LLM integration", "RAG patterns",
    "DevOps", "monitoring", "observability",
    "open source", "developer tools",
    "career advice", "interview preparation",
    "clean code", "design patterns", "refactoring",
    "mobile development", "React Native", "Flutter",
    "cloud providers", "AWS", "GCP", "Azure",
    "web accessibility", "technical writing",
  ],
  education: [
    "study techniques", "spaced repetition", "note-taking methods",
    "curriculum design", "project-based learning",
    "online learning platforms", "MOOCs",
    "math fundamentals", "statistics", "probability",
    "writing skills", "research methodology",
    "critical thinking", "problem-solving frameworks",
    "language learning", "memory techniques",
    "exam preparation", "time management",
    "educational technology", "gamification",
    "teaching strategies", "assessment methods",
    "STEM education", "coding for beginners",
    "academic writing", "presentation skills",
    "learning disabilities", "accessibility in education",
    "career guidance", "skill development",
    "financial literacy", "digital literacy",
  ],
  entertainment: [
    "movie reviews", "TV show analysis", "anime reviews",
    "celebrity interviews", "behind the scenes",
    "comedy sketches", "stand-up comedy",
    "reaction videos", "challenge videos",
    "storytelling", "film techniques", "cinematography",
    "streaming culture", "content creation tips",
    "pop culture trends", "memes and internet culture",
    "fan theories", "Easter eggs",
    "documentary analysis", "true crime",
    "award shows", "box office analysis",
    "independent films", "foreign cinema",
    "podcast highlights", "viral moments",
    "celebrity news", "entertainment industry analysis",
  ],
  gaming: [
    "game reviews", "gameplay walkthroughs",
    "competitive gaming", "esports", "tournament coverage",
    "game development", "indie games",
    "retro gaming", "game history",
    "FPS games", "RPGs", "strategy games", "MMOs",
    "game mechanics analysis", "speedrunning",
    "gaming hardware", "PC building",
    "console comparisons", "handheld gaming",
    "VR gaming", "cloud gaming",
    "game soundtracks", "game art and design",
    "modding community", "game updates and patches",
    "live streaming tips", "content creation for gamers",
    "gaming industry news", "upcoming releases",
  ],
  music: [
    "music theory", "chord progressions", "scales and modes",
    "song analysis", "music production",
    "DAW tutorials", "mixing and mastering",
    "instrument tutorials", "guitar", "piano", "drums",
    "vocal techniques", "singing tips",
    "music history", "genre evolution",
    "album reviews", "concert coverage",
    "music business", "independent artists",
    "sound design", "sampling", "beat making",
    "music technology", "synthesizers",
    "songwriting", "lyric analysis",
    "classical music", "jazz", "electronic music",
    "music copyright", "distribution platforms",
  ],
  news: [
    "breaking news", "current events",
    "political analysis", "policy explainers",
    "economic news", "market analysis",
    "international affairs", "geopolitics",
    "investigative journalism", "fact-checking",
    "media analysis", "press freedom",
    "technology news", "AI policy",
    "climate and environment", "energy policy",
    "health news", "public health",
    "legal analysis", "court decisions",
    "social issues", "inequality",
    "defense and security", "cybersecurity",
    "election coverage", "government accountability",
    "local news", "community impact",
  ],
  sports: [
    "match analysis", "game highlights",
    "player profiles", "transfer news",
    "training techniques", "fitness programs",
    "football/soccer", "basketball", "tennis", "cricket",
    "sports statistics", "data analytics in sports",
    "coaching strategies", "team tactics",
    "sports psychology", "mental performance",
    "nutrition for athletes", "injury prevention",
    "Olympic sports", "extreme sports",
    "sports history", "legendary moments",
    "sports technology", "wearable tech",
    "fantasy sports", "sports betting analysis",
    "women in sports", "youth development",
  ],
  science: [
    "physics", "quantum mechanics", "relativity",
    "chemistry", "organic chemistry", "materials science",
    "biology", "genetics", "evolution",
    "astronomy", "astrophysics", "space exploration",
    "neuroscience", "consciousness studies",
    "climate science", "environmental research",
    "medical research", "drug development",
    "mathematics", "number theory", "topology",
    "computer science theory", "algorithms",
    "scientific method", "peer review",
    "history of science", "famous experiments",
    "biotech", "nanotechnology",
    "AI research", "machine learning theory",
    "science communication", "science policy",
  ],
  lifestyle: [
    "personal finance", "budgeting", "investing",
    "minimalism", "organization", "decluttering",
    "cooking", "recipes", "meal prep",
    "fitness routines", "home workouts", "yoga",
    "mental health", "meditation", "mindfulness",
    "fashion", "style guides", "seasonal trends",
    "home decor", "DIY projects", "renovation",
    "travel", "travel tips", "destination guides",
    "relationships", "dating advice",
    "productivity", "habit building",
    "self-improvement", "goal setting",
    "parenting", "family life",
    "beauty", "skincare", "wellness",
  ],
  other: [
    "general knowledge", "how-to guides",
    "explainers", "deep dives",
    "reviews", "comparisons",
    "tutorials", "tips and tricks",
    "community content", "collaborations",
    "Q&A sessions", "audience interaction",
    "behind the scenes", "day in the life",
    "opinions", "discussions", "debates",
    "top lists", "recommendations",
    "unboxing", "first impressions",
    "reactions", "commentary",
    "vlogs", "documentaries",
  ],
};

const NICHE_CONTEXT: Readonly<Record<ChannelCategory, string>> = {
  technology: "The technology YouTube landscape covers software development, DevOps, cloud computing, AI/ML, web frameworks, mobile development, and developer career content. Trending topics in 2025-2026 include AI agents, LLM integration, Rust adoption, and edge computing.",
  education: "Educational YouTube spans academic subjects, skill development, study techniques, and career guidance. Growing trends include AI-assisted learning, micro-credentials, and interactive coding education.",
  entertainment: "Entertainment YouTube covers movies, TV, comedy, reaction content, and pop culture analysis. Trending: AI in entertainment, streaming wars analysis, and interactive storytelling.",
  gaming: "Gaming YouTube includes reviews, walkthroughs, esports, and game development. Hot topics: AI in games, cloud gaming maturity, VR experiences, and indie game renaissance.",
  music: "Music YouTube spans tutorials, production, theory, reviews, and artist development. Trends: AI music generation ethics, home studio advancement, and independent distribution.",
  news: "News YouTube covers current events, political analysis, investigative journalism, and media criticism. Growing: AI policy coverage, climate reporting, and fact-checking content.",
  sports: "Sports YouTube includes analysis, highlights, training, and fan content. Trends: sports analytics, wearable tech, and women's sports coverage expansion.",
  science: "Science YouTube covers physics, biology, chemistry, space, and research communication. Trending: quantum computing, CRISPR advances, climate solutions, and AI research.",
  lifestyle: "Lifestyle YouTube spans personal finance, fitness, cooking, travel, and self-improvement. Trends: financial independence, mental health awareness, and sustainable living.",
  other: "General content YouTube covers a wide range of topics from how-to guides to commentary and vlogs.",
};

export function getNicheTopics(category: ChannelCategory): ReadonlyArray<string> {
  return NICHE_TOPICS[category] ?? NICHE_TOPICS.other;
}

export function getNicheContext(category: ChannelCategory): string {
  return NICHE_CONTEXT[category] ?? NICHE_CONTEXT.other;
}
